name: Build and deploy digdirator

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'charts/**'
      - '.github/workflows/chart.yaml'
      - '*.md'

jobs:
  build_and_push_registry:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    outputs:
      version: ${{ steps.build_push_sign.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # ratchet:actions/checkout@v3
      - name: Generate version
        id: version
        run: echo "version=$(date +'%Y%m%d-%H%M%S')-$(git rev-parse --short HEAD)" >> ${GITHUB_OUTPUT}
      - name: Install cosign
        uses: sigstore/cosign-installer@9e9de2292db7abb3f51b7f4808d98f0d347a8919 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0'
      - name: Verify builder image
        run: cosign verify --certificate-identity "https://github.com/chainguard-images/images/.github/workflows/release.yaml@refs/heads/main"  --certificate-oidc-issuer "https://token.actions.githubusercontent.com" cgr.dev/chainguard/go:1.20
      - name: Verify runner image
        run: cosign verify --certificate-oidc-issuer https://accounts.google.com  --certificate-identity keyless@distroless.iam.gserviceaccount.com gcr.io/distroless/static-debian11:nonroot
      - uses: nais/build-push-sign@8b336817c5749f179373fd63a7f511bae7246f10 # ratchet:nais/build-push-sign@main
        id: build_push_sign
        with:
          name: digdirator
          dockerfile: Dockerfile
          google_service_account: gh-digdirator
          push: ${{ github.actor != 'dependabot[bot]' && github.ref == 'refs/heads/master' }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}

  rollout:
    permissions:
      id-token: write
    needs: ["build_and_push_registry"]
    runs-on: fasit-deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: nais/fasit-deploy@b2c0b6d049b53bef41b321eec406fe66938576fd # ratchet:nais/fasit-deploy@main
        with:
          json: '{"image": {"tag": "${{ needs.build_and_push_registry.outputs.version }}"}}'
          feature_name: digdirator
